/* This file was generated by gen_romdb.py */

/* Games that need alternate VI timing */
static const uint64_t lut_alternate_vi[] = {
   0x19c553a7a70f4b52ULL, /* Pokemon Puzzle League (U) */
   0x4a1cd153d830aef8ULL, /* Pokemon Puzzle League (E) */
   0x3eb2e6f362f9efeULL,  /* Pokemon Puzzle League (F) */
   0x7a4747ac44eeec23ULL  /* Pokemon Puzzle League (G) */
};

static const uint64_t lut_vi_clock_1500[] = {
   0x19c553a7a70f4b52ULL, /* Pokemon Puzzle League (U) */
   0x4a1cd153d830aef8ULL, /* Pokemon Puzzle League (E) */
   0x3eb2e6f362f9efeULL,  /* Pokemon Puzzle League (F) */
   0x7a4747ac44eeec23ULL  /* Pokemon Puzzle League (G) */
};

static const uint64_t lut_vi_clock_1600[] = {
   0x519EA4E1EB7584E8ULL, /* King Hill 64 - Extreme Snowboarding (J) [!] */
   0xE688A5B8B14B3F18ULL, /* Twisted Edge Extreme Snowboarding (E) [!] */
   0xBBC99D32117DAA80ULL, /* Twisted Edge Extreme Snowboarding (U) [!] */
};

static const uint64_t lut_vi_clock_2200[] = {
   0x7EAE24889D40A35AULL, /* Biohazard 2 (J) [!] */
   0xAF9DCC151A723D88ULL, /* Indiana Jones and the Infernal Machine (U) [!] */
   0x3A6F8C6B2897BAEBULL, /* Indiana Jones and the Infernal Machine (E) */
   0x9B500E8EE90550B3ULL, /* Resident Evil 2 (E) (M2) [!] */
   0x2F493DD02E64DFD9ULL, /* Resident Evil 2 (U) [!] */
   0xAA18B1A507DB6AEBULL, /* Resident Evil 2 (U) (V1.1) [!] */
};

static const uint64_t lut_fixedaudiopos[] = {
   0x519EA4E1EB7584E8ULL, /* King Hill 64 - Extreme Snowboarding (J) [!] */
   0xE688A5B8B14B3F18ULL, /* Twisted Edge Extreme Snowboarding (E) [!] */
   0xBBC99D32117DAA80ULL, /* Twisted Edge Extreme Snowboarding (U) [!] */
};

/* Games that use 16Kbit EEPROM */
static const uint64_t lut_ee16k[] = {
   0x975B7845A2505C18ULL, /* 77a Special Edition by Count0 (PD) */
   0x514B6900B4B19881ULL, /* Banjo to Kazooie no Daibouken 2 (J) [!] */
   0x155B7CDFF0DA7325ULL, /* Banjo-Tooie (A) [!] */
   0xC9176D39EA4779D1ULL, /* Banjo-Tooie (E) (M4) [!] */
   0xC2E9AA9A475D70AAULL, /* Banjo-Tooie (U) [!] */
   0x373F58899A6CA80AULL, /* Conker's Bad Fur Day (E) [!] */
   0x30C7AC507704072DULL, /* Conker's Bad Fur Day (U) [!] */
   0x83F3931ECB72223DULL, /* Cruis'n World (E) [!] */
   0xDFE61153D76118E6ULL, /* Cruis'n World (U) [!] */
   0x11936D8C6F2C4B43ULL, /* Donkey Kong 64 (E) [!] */
   0x053C89A7A5064302ULL, /* Donkey Kong 64 (J) [!] */
   0x0DD4ABABB5A2A91EULL, /* Donkey Kong 64 (U) (Kiosk Demo) [!] */
   0xEC58EABFAD7C7169ULL, /* Donkey Kong 64 (U) [!] */
   0xB6306E99B63ED2B2ULL, /* Doraemon 2 - Nobita to Hikari no Shinden (J) [!] */
   0xA8275140B9B056E8ULL, /* Doraemon 3 - Nobita no Machi SOS! (J) [!] */
   0x202A8EE483F88B89ULL, /* Excitebike 64 (E) [!] */
   0x861C3519F6091CE5ULL, /* Excitebike 64 (J) [!] */
   0xAF754F7B1DD17381ULL, /* Excitebike 64 (U) (Kiosk Demo) [!] */
   0x07861842A12EBC9FULL, /* Excitebike 64 (U) [!] */
   0x1739EFBAD0B43A68ULL, /* Kobe Bryant in NBA Courtside (E) [!] */
   0x616B84948A509210ULL, /* Kobe Bryant's NBA Courtside (U) [!] */
   0xA197CB527520DE0EULL, /* Madden Football 64 (E) [!] */
   0x13836389265B3C76ULL, /* Madden Football 64 (U) [!] */
   0xC56741600F5F453CULL, /* Mario Party 3 (E) (M4) [!] */
   0x0B0AB4CD7B158937ULL, /* Mario Party 3 (J) [!] */
   0x7C3829D96E8247CEULL, /* Mario Party 3 (U) [!] */
   0x839F3AD5406D15FAULL, /* Mario Tennis (E) [!] */
   0x5001CF4FF30CB3BDULL, /* Mario Tennis (U) [!] */
   0x3A6C42B51ACADA1BULL, /* Mario Tennis 64 (J) [!] */
   0x147E0EDB36C5B12CULL, /* Neon Genesis Evangelion (J) [!] */
   0xF468118CE32EE44EULL, /* PD Ultraman Battle Collection 64 (J) [!] */
   0xE4B08007A602FF33ULL, /* Perfect Dark (E) (M5) [!] */
   0x96747EB4104BB243ULL, /* Perfect Dark (J) [!] */
   0xDDF460CC3CA634C0ULL, /* Perfect Dark (U) (V1.0) [!] */
   0x41F2B98FB458B466ULL, /* Perfect Dark (U) (V1.1) [!] */
   0xFEE970104E94A9A0ULL, /* RR64 - Ridge Racer 64 (E) [!] */
   0x2500267E2A7EC3CEULL, /* RR64 - Ridge Racer 64 (U) [!] */
   0x53ED2DC406258002ULL, /* Star Wars Episode I - Racer (E) (M3) [!] */
   0x61F5B152046122ABULL, /* Star Wars Episode I - Racer (J) [!] */
   0x72F703986556A98BULL, /* Star Wars Episode I - Racer (U) [!] */
   0x2DCFCA608354B147ULL, /* Yoshi Story (J) [!] */
   0xD3F97D496924135BULL, /* Yoshi's Story (E) (M3) [!] */
   0x2337D8E86B8E7CECULL  /* Yoshi's Story (U) (M2) [!] */
};


/* Games that use 4Kbit EEPROM */
static const uint64_t lut_ee4k[] = {
   0xB98BA4565B2B76AFULL, /* 64 de Hakken!! Tamagotchi Minna de Tamagotchi World (J) [!] */
   0x36F22FBF318912F2ULL, /* 64 Hanafuda - Tenshi no Yakusoku (J) [!] */
   0x7A6081FCFF8F7A78ULL, /* 64 Trump Collection - Alice no Wakuwaku Trump World (J) [!] */
   0x62F6BE95F102D6D6ULL, /* AeroFighters Assault (E) (M3) [!] */
   0x1B598BF1ECA29B45ULL, /* AeroFighters Assault (U) [!] */
   0x8CC182A6C2D0CAB0ULL, /* AI Shougi 3 (J) [!] */
   0xDFD784ADAE426603ULL, /* All Star Tennis '99 (E) (M5) [!] */
   0xE185E2914E50766DULL, /* All Star Tennis '99 (U) [!] */
   0xE340A49C74318D41ULL, /* Baku Bomberman (J) [!] */
   0xE73C7C4FAF93B838ULL, /* Baku Bomberman 2 (J) [!] */
   0x5168D520CA5FCD0DULL, /* Banjo to Kazooie no Daibouken (J) [!] */
   0x733FCCB1444892F9ULL, /* Banjo-Kazooie (E) (M3) [!] */
   0xA4BF9306BF0CDFD1ULL, /* Banjo-Kazooie (U) (V1.0) [!] */
   0xB088FBB4441E4B1DULL, /* Bass Hunter 64 (E) [!] */
   0x08FFA4B701F453B6ULL, /* Big Mountain 2000 (U) [!] */
   0x7C64E6DB55B924DBULL, /* Blast Corps (E) (M2) [!] */
   0x7C647C25D9D901E6ULL, /* Blast Corps (U) (V1.0) [!] */
   0x7C647E651948D305ULL, /* Blast Corps (U) (V1.1) [!] */
   0x65234451EBD3346FULL, /* Blast Dozer (J) [!] */
   0x0B58B8CDB7B291D2ULL, /* Body Harvest (E) (M3) [!] */
   0x5326696FFE9A99C3ULL, /* Body Harvest (U) [!] */
   0x5A160336BC7B37B0ULL, /* Bomberman 64 (E) [!] */
   0xF568D51E7E49BA1EULL, /* Bomberman 64 (U) [!] */
   0x237E73B4D63B6B37ULL, /* Bomberman 64 - The Second Attack! (U) [!] */
   0xD85C4E2988E276AFULL, /* Bomberman Hero (E) [!] */
   0x4446FDD6E3788208ULL, /* Bomberman Hero (U) [!] */
   0x67FF12CC76BF0212ULL, /* Bomberman Hero - Mirian Oujo wo Sukue! (J) [!] */
   0xB9AF8CC6DEC9F19FULL, /* Chameleon Twist (E) [!] */
   0xA4F2F521F0EB168EULL, /* Chameleon Twist (J) [!] */
   0x6420535A50028062ULL, /* Chameleon Twist (U) [!] */
   0x2E3593393FA5EDA6ULL, /* Chopper Attack (E) [!] */
   0x214CAD94BE1A3B24ULL, /* Chopper Attack (U) [!] */
   0x2BCCF9C4403D9F6FULL, /* Choro Q 64 (J) [!] */
   0xA794152861F1199DULL, /* Chou Snobow Kids (J) [!] */
   0xF8009DB06B291823ULL, /* City-Tour GP - Zennihon GT Senshuken (J) [!] */
   0x46A3F7AF0F7591D0ULL, /* Cruis'n Exotica (U) [!] */
   0x503EA760E1300E96ULL, /* Cruis'n USA (E) [!] */
   0xFF2F2FB4D161149AULL, /* Cruis'n USA (U) (V1.0) [!] */
   0x5306CF45CBC49250ULL, /* Cruis'n USA (U) (V1.1) [!] */
   0xB34025547340C004ULL, /* Cruis'n USA (U) (V1.2) [!] */
   0xFD73F7759724755AULL, /* Diddy Kong Racing (E) (M3) (V1.0) [!] */
   0x596E145BF7D9879FULL, /* Diddy Kong Racing (E) (M3) (V1.1) [!] */
   0xF389A35A17785562ULL, /* Diddy Kong Racing (J) [f1] (Z64) */
   0x7435C9BB39763CF4ULL, /* Diddy Kong Racing (J) */
   0x53D440E77519B011ULL, /* Diddy Kong Racing (U) (M2) (V1.0) [!] */
   0xE402430DD2FCFC9DULL, /* Diddy Kong Racing (U) (M2) (V1.1) [!] */
   0xC16C421BA21580F7ULL, /* Disney's Donald Duck - Goin' Quackers (U) [!] */
   0x3DF17480193DED5AULL, /* Donald Duck - Quack Attack (E) (M5) [!] */
   0xD52FE29D8EA6A759ULL, /* Donchan Puzzle Hanabi de Doon! (J) [ALECK64] */
   0x492B9DE8C6CCC81CULL, /* Earthworm Jim 3D (E) (M6) [!] */
   0xDF5741919EB5123DULL, /* Earthworm Jim 3D (U) [!] */
   0x6D9D1FE484D10BEAULL, /* Eleven Beat - World Tournament (J) [ALECK64] */
   0xCC3CC8B30EC405A4ULL, /* F-1 World Grand Prix (E) [!] */
   0xB70BAEE53A5005A8ULL, /* F-1 World Grand Prix (F) [!] */
   0x3844263466B3F060ULL, /* F-1 World Grand Prix (G) [!] */
   0x64BF47C4F4BD22BAULL, /* F-1 World Grand Prix (J) [!] */
   0x36F1C74BF2029939ULL, /* Fighter's Destiny (E) [!] */
   0x0C41F9C201717A0DULL, /* Fighter's Destiny (F) [!] */
   0xFE94E570E4873A9CULL, /* Fighter's Destiny (G) [!] */
   0x52F788058B8FCAB7ULL, /* Fighter's Destiny (U) [!] */
   0x49E46C2D7B1A110CULL, /* Fighting Cup (J) [!] */
   0xF523730199E3EE93ULL, /* Glover (E) (M3) [!] */
   0x8E6E01FFCCB4F948ULL, /* Glover (U) [!] */
   0x0414CA612E57B8AAULL, /* GoldenEye 007 (E) [!] */
   0xA24F4CF1A82327BAULL, /* GoldenEye 007 (J) [!] */
   0xB57D4EB4345E09E5ULL, /* Guru - Kuru Kuru Fever (J) [ALECK64] */
   0xEE4A0E338FD588C9ULL, /* GT 64 - Championship Edition (E) (M3) [!] */
   0xC49ADCA2F1501B62ULL, /* GT 64 - Championship Edition (U) [!] */
   0xD3F10E5D052EA579ULL, /* Hey You, Pikachu! (U) [!] */
   0xC1D702BD6D416547ULL, /* Hoshi no Kirby 64 (J) (V1.0) [!] */
   0xCA1BB86F41CCA5C5ULL, /* Hoshi no Kirby 64 (J) (V1.1) [!] */
   0x0C581C7A3D6E20E4ULL, /* Hoshi no Kirby 64 (J) (V1.2) [!] */
   0xBCB1F89F060752A2ULL, /* Hoshi no Kirby 64 (J) (V1.3) [!] */
   0x8C138BE095700E46ULL, /* In-Fisherman Bass Hunter 64 (U) [!] */
   0xAF9DCC151A723D88ULL, /* Indiana Jones and the Infernal Machine (U) [!] */
   0x3A6F8C6B2897BAEBULL, /* Indiana Jones and the Infernal Machine (E) */
   0xE436467A82DE8F9BULL, /* Indy Racing 2000 (U) [!] */
   0x979B263EF8470004ULL, /* Killer Instinct Gold (E) [!] */
   0x9E8FE2BA8B270770ULL, /* Killer Instinct Gold (U) (V1.0) [!] */
   0x9E8FCDFA49F5652BULL, /* Killer Instinct Gold (U) (V1.1) [!] */
   0xF908CA4C36464327ULL, /* Killer Instinct Gold (U) (V1.2) [!] */
   0x0D93BA11683868A6ULL, /* Kirby 64 - The Crystal Shards (E) [!] */
   0x46039FB40337822CULL, /* Kirby 64 - The Crystal Shards (U) [!] */
   0x60460680305F0E72ULL, /* Lode Runner 3-D (E) (M5) [!] */
   0x964ADD0BB29213DBULL, /* Lode Runner 3-D (J) [!] */
   0x255018DF57D6AE3AULL, /* Lode Runner 3-D (U) [!] */
   0x2483F22B136E025EULL, /* Lylat Wars (A) (M3) [!] */
   0xF4CBE92CB392ED12ULL, /* Lylat Wars (E) (M3) [!] */
   0xD5356BAC97AE69D2ULL, /* Magical Tetris Challenge Featuring Mickey (J) [ALECK64] */
   0xC3B6DE9D65D2DE76ULL, /* Mario Kart 64 (E) (V1.0) [!] */
   0x2577C7D4D18FAAAEULL, /* Mario Kart 64 (E) (V1.1) [!] */
   0x6BFF4758E5FF5D5EULL, /* Mario Kart 64 (J) (V1.0) [!] */
   0xC9C3A9875810344CULL, /* Mario Kart 64 (J) (V1.1) [!] */
   0x3E5055B62E92DA52ULL, /* Mario Kart 64 (U) [!] */
   0x9C66306980F24A80ULL, /* Mario Party (E) (M3) [!] */
   0xADA815BE6028622FULL, /* Mario Party (J) [!] */
   0x2829657EA0621877ULL, /* Mario Party (U) [!] */
   0x82380387DFC744D9ULL, /* Mario Party 2 (E) (M5) [!] */
   0xED567D0F38B08915ULL, /* Mario Party 2 (J) [!] */
   0x9EA95858AF72B618ULL, /* Mario Party 2 (U) [!] */
   0x736AE6AF4117E9C7ULL, /* Mickey no Racing Challenge USA (J) [!] */
   0xDED0DD9AE78225A7ULL, /* Mickey's Speedway USA (E) (M5) [!] */
   0xFA8C4571BBE7F9C0ULL, /* Mickey's Speedway USA (U) [!] */
   0x418BDA98248A0F58ULL, /* Mischief Makers (E) [!] */
   0x0B93051B603D81F9ULL, /* Mischief Makers (U) [!] */
   0x2256ECDA71AB1B9CULL, /* Mission Impossible (E) [!] */
   0x20095B34343D9E87ULL, /* Mission Impossible (F) [!] */
   0x93EB3F7E81675E44ULL, /* Mission Impossible (G) [!] */
   0xEBA949DC39BAECBDULL, /* Mission Impossible (I) [!] */
   0x5F6A04E2D4FA070DULL, /* Mission Impossible (S) [!] */
   0x26035CF8802B9135ULL, /* Mission Impossible (U) [!] */
   0x5AC383E1D712E387ULL, /* Monopoly (U) [!] */
   0xB8F0BD034479189EULL, /* MRC - Multi Racing Championship (E) (M3) [!] */
   0xA6B6B41315D113CCULL, /* MRC - Multi Racing Championship (J) [!] */
   0x2AF9B65C85E2A2D7ULL, /* MRC - Multi Racing Championship (U) [!] */
   0xC83CEB83FDC56219ULL, /* Penny Racers (E) [!] */
   0x73ABB1FB9CCA6093ULL, /* Penny Racers (U) [!] */
   0xEE08C6026BC2D5A6ULL, /* PGA European Tour (E) (M5) [!] */
   0xB54CE881BCCB6126ULL, /* PGA European Tour (U) [!] */
   0x3F245305FC0B74AAULL, /* Pikachu Genki Dechu (J) [!] */
   0x1AA05AD546F52D80ULL, /* Pilotwings 64 (E) (M3) [!] */
   0x09CC4801E42EE491ULL, /* Pilotwings 64 (J) [!] */
   0xC851961C78FCAAFAULL, /* Pilotwings 64 (U) [!] */
   0x9FD375F845F32DC8ULL, /* Rocket - Robot on Wheels (E) (M3) [!] */
   0x0C5EE085A167DD3EULL, /* Rocket - Robot on Wheels (U) [!] */
   0x2EF4D519C64A0C5EULL, /* Snow Speeder (J) [!] */
   0xC2751D1AF8C19BFFULL, /* Snowboard Kids 2 (E) [!] */
   0x222123514046594BULL, /* Sonic Wings Assault (J) [!] */
   0xFC70E27208FFE7AAULL, /* Space Station Silicon Valley (E) (M7) [!] */
   0xBFE23884EF48EAAFULL, /* Space Station Silicon Valley (J) [!] */
   0xFFCAA7C168858537ULL, /* Star Fox 64 (J) [!] */
   0xA7D015F82289AA43ULL, /* Star Fox 64 (U) (V1.0) [!] */
   0xBA780BA00F21DB34ULL, /* Star Fox 64 (U) (V1.1) [!] */
   0xB703EB2328AAE53AULL, /* Star Soldier - Vanishing Earth (J) [!] */
   0x315C74663A453265ULL, /* Star Soldier - Vanishing Earth (J) [!] [ALECK64] */
   0xDDD93C85DAE381E8ULL, /* Star Soldier - Vanishing Earth (U) [!] */
   0x7EE0E8BB49E411AAULL, /* Star Wars - Rogue Squadron (E) (M3) (V1.0) [!] */
   0x219191C133183C61ULL, /* Star Wars - Rogue Squadron (E) (M3) (V1.1) [!] */
   0x66A24BEC2EADD94FULL, /* Star Wars - Rogue Squadron (U) (M3) [!] */
   0x4D486681AB7D9245ULL, /* Star Wars - Shadows of the Empire (E) [!] */
   0x264D7E5C18874622ULL, /* Star Wars - Shadows of the Empire (U) (V1.0) [!] */
   0x4147B09163251060ULL, /* Star Wars - Shadows of the Empire (U) (V1.1) [!] */
   0x4DD7ED5474F9287DULL, /* Star Wars - Shadows of the Empire (U) (V1.2) [!] */
   0x827E4890958468DCULL, /* Star Wars - Shutsugeki! Rogue Chuutai (J) [!] */
   0xEAE6ACE2020B4384ULL, /* Star Wars Episode I - Battle for Naboo (E) [!] */
   0x3D02989BD4A381E2ULL, /* Star Wars Episode I - Battle for Naboo (U) [!] */
   0xD89E0E55B17AA99AULL, /* Starshot - Space Circus Fever (E) (M3) [!] */
   0x94EDA5B88673E903ULL, /* Starshot - Space Circus Fever (U) (M3) [!] */
   0xA03CF036BCC1C5D2ULL, /* Super Mario 64 (E) (M3) [!] */
   0x4EAA3D0E74757C24ULL, /* Super Mario 64 (J) [!] */
   0x635A2BFF8B022326ULL, /* Super Mario 64 (U) [!] */
   0x85a772f1d5e7cdcaULL, /* Super Mario 64 60fps */
   0xD6FBA4A86326AA2CULL, /* Super Mario 64 - Shindou Edition (J) [!] */
   0x0FE684A98BB77AC4ULL, /* Tetrisphere (E) [!] */
   0x3C1FDABE02A4E0BAULL, /* Tetrisphere (U) [!] */
   0x2B4F4EFB43C511FEULL, /* Tom and Jerry in Fists of Furry (E) (M6) [!] */
   0x63E7391CE6CCEA33ULL, /* Tom and Jerry in Fists of Furry (U) [!] */
   0xD09BA5381C1A5489ULL, /* Top Gear Overdrive (E) [!] */
   0x0578F24F9175BF17ULL, /* Top Gear Overdrive (J) [!] */
   0xD741CD80ACA9B912ULL, /* Top Gear Overdrive (U) [!] */
   0x90AF8D2CE1AC1B37ULL, /* Tower & Shaft (J) [ALECK64] */
   0x636E6B19E57DDC5FULL, /* V-Rally Edition 99 (E) (M3) [!] */
   0x4D0224A51BEB5794ULL, /* V-Rally Edition 99 (J) [!] */
   0x3C059038C8BF2182ULL, /* V-Rally Edition 99 (U) [!] */
   0x2F57C9F7F1E29CA6ULL, /* Vivid Dolls (J) [ALECK64] */
   0x93053075261E0F43ULL, /* Waialae Country Club - True Golf Classics (E) (M4) (V1.0) [!] */
   0x0C5057AD046E126EULL, /* Waialae Country Club - True Golf Classics (E) (M4) (V1.1) [!] */
   0x8066D58AC3DECAC1ULL, /* Waialae Country Club - True Golf Classics (U) (V1.0) [!] */
   0x650EFA9630DDF9A7ULL, /* Wave Race 64 (E) (M2) [!] */
   0x5C9191D6B30AC306ULL, /* Wave Race 64 (J) [!] */
   0x7DE11F5374872F9DULL, /* Wave Race 64 (U) (V1.0) [!] */
   0x492F4B6104E5146AULL, /* Wave Race 64 (U) (V1.1) [!] */
   0x535DF3E2609789F1ULL, /* Wave Race 64 - Shindou Edition (J) (V1.2) [!] */
   0x0CEBC4C70C9CE932ULL, /* Wild Choppers (J) [!] */
   0x2D21C57B8FE4C58CULL, /* Worms - Armageddon (E) (M6) [!] */
   0x13E959A00E93CAB0ULL, /* Worms - Armageddon (U) (M3) [!] */
   0x9FE6162DE97E4037ULL  /* Yuke Yuke!! Trouble Makers (J) [!] */
};

/* Games that use Flash RAM */
static const uint64_t lut_flashram[] = {
   0xAE5B9465C54D6576ULL, /* Command & Conquer (E) (M2) [!] */
   0xB5025BADD32675FDULL, /* Command & Conquer (G) [!] */
   0x95286EB4B76AD58FULL, /* Command & Conquer (U) [!] */
   0x68D7A1DE0079834AULL, /* Jet Force Gemini (E) (M4) [!] */
   0x8A6009B694ACE150ULL, /* Jet Force Gemini (U) [!] */
   0x36281F23009756CFULL, /* Ken Griffey Jr.'s Slugfest (U) [!] */
   0xE97955C6BC338D38ULL, /* Legend of Zelda, The - Majora's Mask (E) (M4) (V1.0) [!] */
   0x0A5D8F8398C5371AULL, /* Legend of Zelda, The - Majora's Mask (E) (M4) (V1.1) */
   0x5354631C03A2DEF0ULL, /* Legend of Zelda, The - Majora's Mask (U) [!] */
   0xB443EB084DB31193ULL, /* Legend of Zelda, The - Majora's Mask (U) (GC) */
   0x0EC158F5FB3E6896ULL, /* Mega Man 64 (U) [!] */
   0x916852D873DBEAEFULL, /* NBA Courtside 2 - Featuring Kobe Bryant (U) [!] */
   0x3BA7CDDC464E52A0ULL, /* Mario Story (J) [!] */
   0x19AB29AFC71BCD28ULL, /* Paper Mario (E) (M4) [!] */
   0x65EEE53AED7D733CULL, /* Paper Mario (U) [!] */
   0xEC0F690D32A7438CULL, /* Pocket Monsters Snap (J) [!] */
   0x637758865FB80E7BULL, /* Pocket Monsters Stadium 2 (J) [!] */
   0xEE4FD7C29CF1D938ULL, /* Pocket Monsters Stadium Kin Gin (J) [!] */
   0x4A1CD153D830AEF8ULL, /* Pokemon Puzzle League (E) [!] */
   0x3EB2E6F3062F9EFEULL, /* Pokemon Puzzle League (F) [!] */
   0x7A4747AC44EEEC23ULL, /* Pokemon Puzzle League (G) [!] */
   0x19C553A7A70F4B52ULL, /* Pokemon Puzzle League (U) [!] */
   0x7BB18D4083138559ULL, /* Pokemon Snap (A) [!] */
   0x4FF5976FACF559D8ULL, /* Pokemon Snap (E) [!] */
   0xBA6C293A9FAFA338ULL, /* Pokemon Snap (F) [!] */
   0x5753720D2A8A884DULL, /* Pokemon Snap (G) [!] */
   0xC0C8504661051B05ULL, /* Pokemon Snap (I) [!] */
   0x817D286AEF417416ULL, /* Pokemon Snap (S) [!] */
   0xCA12B54771FA4EE4ULL, /* Pokemon Snap (U) [!] */
   0x8407727557315B9CULL, /* Pokemon Stadium (E) (V1.0) [!] */
   0x91C9E05DAD3AAFB9ULL, /* Pokemon Stadium (E) (V1.1) [!] */
   0xA23553A342BF2D39ULL, /* Pokemon Stadium (F) [!] */
   0x42011E1BE3552DB5ULL, /* Pokemon Stadium (G) [!] */
   0xA53FA82DDAE2C15DULL, /* Pokemon Stadium (I) [!] */
   0xB6E549CEDC8134C0ULL, /* Pokemon Stadium (S) [!] */
   0x90F5D9B39D0EDCF0ULL, /* Pokemon Stadium (U) (V1.0) [!] */
   0x1A122D43C17DAF0FULL, /* Pokemon Stadium (U) (V1.1) [!] */
   0x2952369CB6E4C3A8ULL, /* Pokemon Stadium 2 (E) [!] */
   0xAC5AA5C7A9B0CDC3ULL, /* Pokemon Stadium 2 (F) [!] */
   0x439B7E7EC1A1495DULL, /* Pokemon Stadium 2 (G) [!] */
   0xEFCEAF0022094848ULL, /* Pokemon Stadium 2 (I) [!] */
   0xD0A1FC5B2FB8074BULL, /* Pokemon Stadium 2 (S) [!] */
   0x03571182892FD06DULL, /* Pokemon Stadium 2 (U) [!] */
   0xD666593BD7A25C07ULL, /* Rockman Dash (J) [!] */
   0xF163A242F2449B3BULL, /* Star Twins (J) [!] */
   0xBC9B2CC34ED04DA5ULL, /* StarCraft 64 (Beta) */
   0x42CF5EA39A1334DFULL, /* StarCraft 64 (E) [!] */
   0x0684FBFB5D3EA8A5ULL, /* StarCraft 64 (U) [!] */
   0xE0C4F72F769E1506ULL, /* Tigger's Honey Hunt (E) (M7) [!] */
   0x4EBFDD33664C9D84ULL, /* Tigger's Honey Hunt (U) [!] */
   0x6D8DF08ED008C3CFULL, /* WWF No Mercy (E) (V1.0) [!] */
   0x8CDB94C2CB46C6F0ULL, /* WWF No Mercy (E) (V1.1) [!] */
   0x4E4B06401B49BCFBULL, /* WWF No Mercy (U) (V1.0) [!] */
   0xF7F52DB82195E636ULL, /* Zelda no Densetsu - Toki no Ocarina - Zelda Collection Version (J) (GC) [!] */
   0xF611F4BAC584135CULL, /* Zelda no Densetsu - Toki no Ocarina GC (J) (GC) [!] */
   0xF43B45BA2F0E9B6FULL  /* Zelda no Densetsu - Toki no Ocarina GC URA (J) (GC) [!] */
};

/* (Delay SI) */
static const uint64_t lut_delaysi[][2] = {
   { 0x514B6900B4B19881ULL, 0 }, /* Banjo to Kazooie no Daibouken 2 (J) [!] */
   { 0xC2E9AA9A475D70AAULL, 0 }, /* Banjo-Tooie (U) [!] */
   { 0xC9176D39EA4779D1ULL, 0 }, /* Banjo-Tooie (E) (M4) [!] */
   { 0x155B7CDFF0DA7325ULL, 0 }, /* Banjo-Tooie (A) [!] */
   { 0x418BDA98248A0F58ULL, 0 }, /* Mischief Makers (E) [!] */
   { 0x0B93051B603D81F9ULL, 0 }, /* Mischief Makers (U) [!] */
   { 0x9FE6162DE97E4037ULL, 0 }, /* Yuke Yuke!! Trouble Makers (J) [!] */
   { 0x9F8B96C3A01194DCULL, 0 }, /* Yakouchuu II - Satsujin Kouro (J) */
};

static const uint64_t lut_audiosignal[] = {
   0xD614E5BFA76DBCC1ULL, /* Disney's Tarzan (E) [!] */
   0x001A3BD0AFB3DE1AULL, /* Disney's Tarzan (F) [!] */
   0x4C2613234F295E1AULL, /* Disney's Tarzan (G) [!] */
   0xCBFE69C7F2C0AB2AULL, /* Disney's Tarzan (U) [!] */
   0xB58988E9B1FC4BE8ULL, /* Hydro Thunder (E) [!] */
   0x29A045CEABA9060EULL, /* Hydro Thunder (F) [!] */
   0xC8DC65EB3D8C8904ULL, /* Hydro Thunder (U) [!] */
   0x3FFE80F4A7C15F7EULL, /* NBA Showtime - NBA on NBC (U) [!] */
   0x1FC215320B6466D4ULL, /* Rugrats in Paris - The Movie */
};

static const uint64_t lut_sidmaduration[][2] = {
   { 0x963adba6f7d5c89bULL, 0x64}, /* Tetris 64 (J) */
};

/* Cycles per emulated instruction (aka CountPerOp) */
static const uint64_t lut_cpop[][2] = {
   { 0xB98BA4565B2B76AFULL, 1 }, /* 64 de Hakken!! Tamagotchi Minna de Tamagotchi World (J) [!] */
   { 0x9C961069F5EA488DULL, 1 }, /* 64 Oozumou (J) [!] */
   { 0x27C425D08C2D99C1ULL, 1 }, /* Airboarder 64 (E) [!] */
   { 0x6C45B60CDCE50E30ULL, 1 }, /* Airboarder 64 (J) [!] */
   { 0xB088FBB4441E4B1DULL, 1 }, /* Bass Hunter 64 (E) [!] */
   { 0xD76333AC0CB6219DULL, 1 }, /* Bass Rush - ECOGEAR PowerWorm Championship (J) [!] */
   { 0xBCFACCAAB814D8EFULL, 1 }, /* Bassmasters 2000 (U) [!] */
   { 0x6AA4DDE7E3E2F4E7ULL, 3 }, /* BattleTanx (U) [!] */
   { 0x75A4E2476008963DULL, 3 }, /* BattleTanx - Global Assault (U) [!] */
   { 0xA1B64A61D014940BULL, 3 }, /* Beetle Adventure Racing! (E) (M3) [!] */
   { 0x0B58B8CDB7B291D2ULL, 1 }, /* Body Harvest (E) (M3) [!] */
   { 0x5326696FFE9A99C3ULL, 1 }, /* Body Harvest (U) [!] */
   { 0x8F12C09645DC17E1ULL, 1 }, /* Bug's Life, A (E) [!] */
   { 0x2B38AEC06350B810ULL, 1 }, /* Bug's Life, A (F) [!] */
   { 0xDFF227D90D4D8169ULL, 1 }, /* Bug's Life, A (G) [!] */
   { 0xF63B89CE4582D57DULL, 1 }, /* Bug's Life, A (I) [!] */
   { 0x82DC04FDCF2D82F4ULL, 1 }, /* Bug's Life, A (U) [!] */
   { 0xAC16400ECF5D071AULL, 1 }, /* California Speed (U) [!] */
   { 0x580162ECE3108BF1ULL, 1 }, /* Carmageddon 64 (E) (M4) (Eng-Spa-Fre-Ger) [!] */
   { 0xE48E01F5E6E51F9BULL, 1 }, /* Carmageddon 64 (E) (M4) (Eng-Spa-Fre-Ita) [!] */
   { 0xF00F2D4E340FAAF4ULL, 1 }, /* Carmageddon 64 (U) [!] */
   { 0xFB3C48D08D28F69FULL, 1 }, /* Charlie Blast's Territory (E) [!] */
   { 0x1E0E96E84E28826BULL, 1 }, /* Charlie Blast's Territory (U) [!] */
   { 0xF8009DB06B291823ULL, 1 }, /* City-Tour GP - Zennihon GT Senshuken (J) [!] */
   { 0x373F58899A6CA80AULL, 3 }, /* Conker's Bad Fur Day (E) [!] */
   { 0x30C7AC507704072DULL, 3 }, /* Conker's Bad Fur Day (U) [!] */
   { 0x630AA37D896BD7DBULL, 1 }, /* Destruction Derby 64 (E) (M3) [!] */
   { 0xDEE584A20F161187ULL, 1 }, /* Destruction Derby 64 (U) [!] */
   { 0xC16C421BA21580F7ULL, 3 }, /* Disney's Donald Duck - Goin' Quackers (U) [!] */
   { 0xD614E5BFA76DBCC1ULL, 1 }, /* Disney's Tarzan (E) [!] */
   { 0x001A3BD0AFB3DE1AULL, 1 }, /* Disney's Tarzan (F) [!] */
   { 0x4C2613234F295E1AULL, 1 }, /* Disney's Tarzan (G) [!] */
   { 0xCBFE69C7F2C0AB2AULL, 1 }, /* Disney's Tarzan (U) [!] */
   { 0x3DF17480193DED5AULL, 3 }, /* Donald Duck - Quack Attack (E) (M5) [!] */
   { 0xD52FE29D8EA6A759ULL, 1 }, /* Donchan Puzzle Hanabi de Doon! (J) [ALECK64] */
   { 0x11936D8C6F2C4B43ULL, 1 }, /* Donkey Kong 64 (E) [!] */
   { 0x053C89A7A5064302ULL, 1 }, /* Donkey Kong 64 (J) [!] */
   { 0x0DD4ABABB5A2A91EULL, 1 }, /* Donkey Kong 64 (U) (Kiosk Demo) [!] */
   { 0xEC58EABFAD7C7169ULL, 1 }, /* Donkey Kong 64 (U) [!] */
   { 0xFBB9F1FA6BF88689ULL, 1 }, /* Duck Dodgers Starring Daffy Duck (U) (M3) [!] */
   { 0xDC36626A3F3770CBULL, 1 }, /* Duke Nukem - ZER0 H0UR (E) [!] */
   { 0x32CA974BB2C29C50ULL, 1 }, /* Duke Nukem - ZER0 H0UR (F) [!] */
   { 0x04DAF07F0D18E688ULL, 1 }, /* Duke Nukem - ZER0 H0UR (U) [!] */
   { 0x6D9D1FE484D10BEAULL, 1 }, /* Eleven Beat - World Tournament (J) [ALECK64] */
   { 0x202A8EE483F88B89ULL, 1 }, /* Excitebike 64 (E) [!] */
   { 0x07861842A12EBC9FULL, 1 }, /* Excitebike 64 (U) [!] */
   { 0x66CF0FFEAD697F9CULL, 1 }, /* Fighting Force 64 (E) [!] */
   { 0x32EFC7CBC3EA3F20ULL, 1 }, /* Fighting Force 64 (U) [!] */
   { 0x22E9623FB60E52ADULL, 1 }, /* Flying Dragon (E) [!] */
   { 0xA92D52E51D26B655ULL, 1 }, /* Flying Dragon (U) [!] */
   { 0xF774EAEEF0D8B13EULL, 1 }, /* Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou! (J) [!] */
   { 0xEE4A0E338FD588C9ULL, 1 }, /* GT 64 - Championship Edition (E) (M3) [!] */
   { 0xC49ADCA2F1501B62ULL, 1 }, /* GT 64 - Championship Edition (U) [!] */
   { 0xB57D4EB4345E09E5ULL, 1 }, /* Guru - Kuru Kuru Fever (J) [ALECK64] */
   { 0x95A80114E0B72A7FULL, 1 }, /* Hamster Monogatari 64 (J) [!] */
   { 0x775AFA9C0EB52EF6ULL, 1 }, /* Hard Coded Demo by Silo and Fractal (PD) [a1] */
   { 0x98DF9DFC6606C189ULL, 1 }, /* Harvest Moon 64 (U) [!] */
   { 0xAE90DBEB79B89123ULL, 1 }, /* Hercules - The Legendary Journeys (E) (M6) [!] */
   { 0x7F3CEB778981030AULL, 1 }, /* Hercules - The Legendary Journeys (U) [!] */
   { 0x95B2B30B2B6415C1ULL, 1 }, /* Hexen (E) [!] */
   { 0x5C1B5FBD7E961634ULL, 1 }, /* Hexen (F) [!] */
   { 0x9AB3B50ABC666105ULL, 1 }, /* Hexen (G) [!] */
   { 0x66751A5754A29D6EULL, 1 }, /* Hexen (J) [!] */
   { 0x35FF8F1A6E79E3BEULL, 1 }, /* Hiryuu no Ken Twin (J) [!] */
   { 0x72611D7D9919BDD2ULL, 3 }, /* HSV Adventure Racing (A) [b1] */
   { 0xB58988E9B1FC4BE8ULL, 1 }, /* Hydro Thunder (E) [!] */
   { 0x29A045CEABA9060EULL, 1 }, /* Hydro Thunder (F) [!] */
   { 0xC8DC65EB3D8C8904ULL, 1 }, /* Hydro Thunder (U) [!] */
#ifndef GLES
   { 0x979B263EF8470004ULL, 1 }, /* Killer Instinct Gold (E) [!] */
   { 0x9E8FE2BA8B270770ULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [!] */
   { 0xCB06B744633194DBULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [b1][t1] */
   { 0x06CB44B73163DB94ULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [b2] */
   { 0x9E8FE2BA8B270770ULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [o1] */
   { 0x06CB44B73163DB94ULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [t1] */
   { 0xCB06B744633194DBULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [t2] */
   { 0x9E8FCDFA49F5652BULL, 1 }, /* Killer Instinct Gold (U) (V1.1) [!] */
   { 0xF908CA4C36464327ULL, 1 }, /* Killer Instinct Gold (U) (V1.2) [!] */
   { 0x06CB44B73163DB94ULL, 1 }, /* Killer Instinct Gold (U) (V1.2) [b1] */
   { 0xF908CA4C36464327ULL, 1 }, /* Killer Instinct Gold (U) (V1.2) [o1] */
#endif
   { 0xAF9DCC151A723D88ULL, 1 }, /* Indiana Jones and the Infernal Machine (U) [!] */
   { 0x3A6F8C6B2897BAEBULL, 1 }, /* Indiana Jones and the Infernal Machine (E) */
   { 0x8C138BE095700E46ULL, 1 }, /* In-Fisherman Bass Hunter 64 (U) [!] */
   { 0xE2D37CF0F57E4EAEULL, 1 }, /* International Superstar Soccer 64 (E) [!] */
   { 0x5F2763C462412AE5ULL, 1 }, /* International Superstar Soccer 64 (U) [!] */
   { 0x6EDD4766A93E9BA8ULL, 3 }, /* Jikkyou Powerful Pro Yakyuu - Basic Han 2001 (J) [!] */
   { 0xE0A79F8C32CC97FAULL, 1 }, /* Jikkyou World Soccer 3 (J) [!] */
   { 0xF478D8B39716DD6DULL, 3 }, /* LEGO Racers (E) (M10) [!] */
   { 0x096A40EA8ABE0A10ULL, 3 }, /* LEGO Racers (U) (M10) [b1] */
   { 0xFBB9F1FA6BF88689ULL, 1 }, /* Lt. Duck Dodgers (Prototype) */
   { 0x0CB816865FD85A81ULL, 1 }, /* Madden NFL 2000 (U) [!] */
   { 0xEB38F792190EA246ULL, 1 }, /* Madden NFL 2001 (U) [!] */
   { 0xD7134F8DC11A00B5ULL, 1 }, /* Madden NFL 2002 (U) [!] */
   { 0x3925D6258C83C75EULL, 1 }, /* Madden NFL 99 (E) [!] */
   { 0xDEB78BBA52F6BD9DULL, 1 }, /* Madden NFL 99 (U) [!] */
   { 0xD5356BAC97AE69D2ULL, 1 }, /* Magical Tetris Challenge Featuring Mickey (J) [ALECK64] */
   { 0x9C66306980F24A80ULL, 1 }, /* Mario Party (E) (M3) [!] */
   { 0xADA815BE6028622FULL, 1 }, /* Mario Party (J) [!] */
   { 0x2829657EA0621877ULL, 1 }, /* Mario Party (U) [!] */
   { 0x82380387DFC744D9ULL, 1 }, /* Mario Party 2 (E) (M5) [!] */
   { 0xED567D0F38B08915ULL, 1 }, /* Mario Party 2 (J) [!] */
   { 0x9EA95858AF72B618ULL, 1 }, /* Mario Party 2 (U) [!] */
   { 0xC56741600F5F453CULL, 1 }, /* Mario Party 3 (E) (M4) [!] */
   { 0x0B0AB4CD7B158937ULL, 1 }, /* Mario Party 3 (J) [!] */
   { 0x7C3829D96E8247CEULL, 1 }, /* Mario Party 3 (U) [!] */
   { 0x5AC383E1D712E387ULL, 1 }, /* Monopoly (U) [!] */
   { 0xD3D806FCB43AA2A8ULL, 3 }, /* Monster Truck Madness 64 (E) (M5) [!] */
   { 0xB19AD9997E585118ULL, 3 }, /* Monster Truck Madness 64 (U) [!] */
   { 0x7F9345D3841ECADEULL, 1 }, /* Mystical Ninja 2 Starring Goemon (E) (M3) [!] */
   { 0xA292524F3D6C2A49ULL, 1 }, /* NBA In the Zone '99 (U) [!] */
   { 0x3FFE80F4A7C15F7EULL, 1 }, /* NBA Showtime - NBA on NBC (U) [!] */
   { 0x2857674DCC4337DAULL, 1 }, /* Nightmare Creatures (U) [!] */
   { 0xCD3C3CDF317793FAULL, 1 }, /* Nintama Rantarou 64 Game Gallery (J) [!] */
   { 0x8A97A197272DF6C1ULL, 1 }, /* Nuclear Strike 64 (E) (M2) [!] */
   { 0x8F50B845D729D22FULL, 1 }, /* Nuclear Strike 64 (G) [!] */
   { 0x4998DDBBF7B7AEBCULL, 1 }, /* Nuclear Strike 64 (U) [!] */
   { 0xD83BB920CC406416ULL, 1 }, /* Nushi Tsuri 64 (J) [!] */
   { 0x3BA7CDDC464E52A0ULL, 1 }, /* Mario Story (J) [!] */
   { 0x19AB29AFC71BCD28ULL, 1 }, /* Paper Mario (E) (M4) [!] */
   { 0x65EEE53AED7D733CULL, 1 }, /* Paper Mario (U) [!] */
   { 0x1AA05AD546F52D80ULL, 3 }, /* Pilotwings 64 (E) (M3) [!] */
   { 0x09CC4801E42EE491ULL, 3 }, /* Pilotwings 64 (J) [!] */
   { 0xC851961C78FCAAFAULL, 3 }, /* Pilotwings 64 (U) [!] */
   { 0x9BA10C4E0408ABD3ULL, 1 }, /* Pro Mahjong Kiwame 64 (J) [!] */
   { 0x1BDCB30FA132D876ULL, 1 }, /* Pro Mahjong Tsuwamono 64 - Jansou Battle ni Chousen (J) [!] */
   { 0x3918834A15B50C29ULL, 1 }, /* Razor Freestyle Scooter (U) [!] */
   { 0xE921953313FBAFBDULL, 1 }, /* Ready 2 Rumble Boxing - Round 2 (U) [!] */
   { 0x02D8366A6CABEF9CULL, 3 }, /* Road Rash 64 (E) [!] */
   { 0xF050746C247B820BULL, 3 }, /* Road Rash 64 (U) [!] */
   { 0x0B6B4DDB9671E682ULL, 1 }, /* Roadsters Trophy (U) (M3) [!] */
   { 0xB7CF2136FA0AA715ULL, 1 }, /* Rush 2 - Extreme Racing USA (E) (M6) [!] */
   { 0xEDD6E03168136013ULL, 1 }, /* Rush 2 - Extreme Racing USA (U) [!] */
   { 0x51D29418D5B46AE3ULL, 1 }, /* San Francisco Rush 2049 (E) (M6) [!] */
   { 0xB9A9ECA217AAE48EULL, 1 }, /* San Francisco Rush 2049 (U) [!] */
   { 0x315C74663A453265ULL, 1 }, /* Star Soldier - Vanishing Earth (J) [!] [ALECK64] */
   { 0x60C437E5A2251EE3ULL, 1 }, /* Shadow Man (E) (M3) [!] */
   { 0xEA06F8C307C2DEEDULL, 1 }, /* Shadow Man (F) [!] */
   { 0x84D5FD75BBFD3CDFULL, 1 }, /* Shadow Man (G) [!] */
   { 0x3A4760B52D74D410ULL, 1 }, /* Shadow Man (U) [!] */
   { 0xD137A2CA62B65053ULL, 1 }, /* Shigesato Itoi's No. 1 Bass Fishing! Definitive Edition (J) [!] */
   { 0xA3A044B56DB1BF5EULL, 1 }, /* Spacer by Memir (POM '99) (PD) */
   { 0xE0C4F72F769E1506ULL, 1 }, /* Tigger's Honey Hunt (E) (M7) [!] */
   { 0x4EBFDD33664C9D84ULL, 1 }, /* Tigger's Honey Hunt (U) [!] */
   { 0x90AF8D2CE1AC1B37ULL, 1 }, /* Tower & Shaft (J) [ALECK64] */
   { 0xCCEB385826952D97ULL, 1 }, /* Toy Story 2 (E) [!] */
   { 0xCB93DB977F5C63D5ULL, 1 }, /* Toy Story 2 (F) [!] */
   { 0x782A9075E552631DULL, 1 }, /* Toy Story 2 (G) [!] */
   { 0xA150743ECF2522CDULL, 1 }, /* Toy Story 2 (U) [!] */
   { 0xFE4B6B43081D29A7ULL, 1 }, /* Triple Play 2000 (U) [!] */
   { 0x28D5562DE4D5AE50ULL, 1 }, /* Uchhannanchan no Hono no Challenger - Denryu IraIra Bou (J) [!] */
   { 0x98F9F2D003D9F09CULL, 1 }, /* Virtual Pool 64 (E) [!] */
   { 0x4E4A7643A37439D7ULL, 1 }, /* Virtual Pool 64 (U) [!] */
   { 0x2F57C9F7F1E29CA6ULL, 1 }, /* Vivid Dolls (J) [ALECK64] */
   { 0xD715CC70271CF5D6ULL, 1 }, /* War Gods (E) [!] */
   { 0xF7FE28F6C3F2ACC3ULL, 1 }, /* War Gods (U) [!] */
   { 0x535DF3E2609789F1ULL, 3 }, /* Wave Race 64 - Shindou Edition (J) (V1.2) [!] */
   { 0xD4C45A1AF425B25EULL, 3 }, /* WCW Nitro (U) [!] */
   { 0x68E8A8750CE7A486ULL, 1 }, /* WCW-nWo Revenge (E) [!] */
   { 0xDEE596ABAF3B7AE7ULL, 1 }, /* WCW-nWo Revenge (U) [!] */
   { 0xCEA8B54F7F21D503ULL, 3 }, /* Wetrix (E) (M6) [!] */
   { 0xDCB6EAFAC6BBCFA3ULL, 3 }, /* Wetrix (J) [!] */
   { 0x54310E7D6B5430D8ULL, 1 }, /* Wipeout 64 (E) [!] */
   { 0x132D2732C70E9118ULL, 1 }, /* Wipeout 64 (U) [!] */
   { 0x9F8B96C3A01194DCULL, 1 }, /* Yakouchuu II - Satsujin Kouro (J) */
   { 0x0553AE9DEAD8E0C1ULL, 3 }, /* Xena Warrior Princess - The Talisman of Fate (U) [!] */
   { 0x0A1667C7293346A6ULL, 3 }, /* Xena Warrior Princess - The Talisman of Fate (E) [!] */
};
